FROM python:2.7.14

# Install Node.js / nodemon
RUN wget --no-check-certificate -nc -P /tmp/bitnami/pkg/cache/ https://downloads.bitnami.com/files/stacksmith/node-8.9.3-0-linux-x64-debian-8.tar.gz && \
    tar -zxf /tmp/bitnami/pkg/cache/node-8.9.3-0-linux-x64-debian-8.tar.gz -P --transform 's|^.*/files|/opt/bitnami|' --wildcards '*/files' && \
    rm -rf /tmp/bitnami/pkg/cache/node-8.9.3-0-linux-x64-debian-8.tar.gz
ENV PATH="/opt/bitnami/node/bin:$PATH"
RUN npm install -g nodemon

# Use non root user
RUN groupadd user && useradd --create-home --home-dir /home/user -g user user

# Configuration
COPY celery/celery-config.cfg /etc/kernelci/kernelci-celery.cfg

# Logs folder
RUN mkdir -p /var/www/images/kernel-ci

# Give additional rights on /var/www
RUN chown -R user:user /etc/kernelci /var/www

# Copy backend source code and give rigth to user
COPY kernelci-backend /home/user/kernelci-backend
RUN chown -R user:user /home/user/kernelci-backend

# Install python dependencies
RUN pip install -r /home/user/kernelci-backend/requirements.txt

# Dedicated entrypoint
COPY celery/entrypoint.sh /srv/entrypoint.sh

# Run application using newly created user
USER user
CMD ["/srv/entrypoint.sh"]
