FROM bitnami/minideb:buster

RUN install_packages git python python-pip python-setuptools python-dev build-essential
RUN pip install python-dateutil

RUN mkdir -p /etc/kernelci
COPY celery-config.cfg /etc/kernelci/kernelci-celery.cfg

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user

WORKDIR /home/user
RUN git clone https://github.com/kernelci/kernelci-backend.git

RUN pip install -r kernelci-backend/requirements.txt

USER user
WORKDIR /home/user/kernelci-backend/app
CMD ["celery", "beat", "--schedule=/var/run/celery/kernelci-beat.db", "--app=taskqueue", "--broker=redis://redis:6379/0", "--pid=/tmp/celery-beat.pid"]
